// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDneldQEDlEQnI6Rk0ofS4yiOVFMTUubI',
    appId: '1:575930815236:web:ec8b8162a9f13509d33651',
    messagingSenderId: '575930815236',
    projectId: 'capstone-v3',
    authDomain: 'capstone-v3.firebaseapp.com',
    storageBucket: 'capstone-v3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA25nlsjmD3FtJhB6NEL8v0-8tZsyTrML4',
    appId: '1:575930815236:android:2abd9122009b3da7d33651',
    messagingSenderId: '575930815236',
    projectId: 'capstone-v3',
    storageBucket: 'capstone-v3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDiShURdBNLagFSma-4V8MxBGWwcsugJw',
    appId: '1:575930815236:ios:033443780d3fa7abd33651',
    messagingSenderId: '575930815236',
    projectId: 'capstone-v3',
    storageBucket: 'capstone-v3.appspot.com',
    iosClientId: '575930815236-fpeu7vae86m6ihb97hcjo2dirrd4ncn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileGuildForJobseekersV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDiShURdBNLagFSma-4V8MxBGWwcsugJw',
    appId: '1:575930815236:ios:033443780d3fa7abd33651',
    messagingSenderId: '575930815236',
    projectId: 'capstone-v3',
    storageBucket: 'capstone-v3.appspot.com',
    iosClientId: '575930815236-fpeu7vae86m6ihb97hcjo2dirrd4ncn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileGuildForJobseekersV3',
  );
}
